### ISSUE TITLE
[Bug]: Install via Git URL doesn't work

### ISSUE THREAD

**Issue by DavidAllenNeron** [Comfy-Org/desktop#486]
App VersionI'm having some issues with the new SANA model and one of the fixes is installing via the Git URL although when I click the button nothing happens.

Someone suggested that I set the security level in the config.ini to weak
located here: C:\Users\xXx\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\config.ini

I have done that but it still won't work. I click the Install via Git URL and nothing happens and I can't see anything in the log/terminal window.

Expected BehaviorClick Install via Git URL to install

Actual Behaviornothing happens at all.

Steps to Reproduce[default]
preview_method = auto
badge_mode = none
git_exe = 
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
share_option = none
bypass_ssl = False
file_logging = True
default_ui = none
component_policy = workflow
double_click_policy = copy-all
windows_selector_event_loop_policy = False
model_download_by_agent = False
downgrade_blacklist = 
security_level = weak

Debug LogsNothing shows up in the logs when I click the button.Browser Logs9
comfyui-manager.js:762 Uncaught 
Error: prompt() is and will not be supported.
    at HTMLButtonElement.onclick (comfyui-manager.js:762:17)
comfyui-manager.js:762 Uncaught 
Error: prompt() is and will not be supported.
    at HTMLButtonElement.onclick (comfyui-manager.js:762:17)

Setting JSON{
  "Comfy-Desktop.AutoUpdate": true,
  "Comfy-Desktop.SendStatistics": false,
  "Comfy.ColorPalette": "dark",
  "Comfy.UseNewMenu": "Top",
  "Comfy.Workflow.WorkflowTabsPosition": "Topbar",
  "Comfy.Workflow.ShowMissingModelsWarning": true,
  "Comfy.Server.LaunchArgs": {},
  "Comfy.LinkRenderMode": 1,
  "Comfy.NodeLibrary.Bookmarks": [],
  "Comfy.CustomColorPalettes": {
    "obsidian": {
      "version": 105,
      "id": "obsidian",
      "name": "Obsidian",
      "colors": {
        "node_slot": {
          "CLIP": "#FFD500",
          "CLIP_VISION": "#A8DADC",
          "CLIP_VISION_OUTPUT": "#

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1970-Bug-Install-via-Git-URL-doesn-t-work-15f6d73d365081b692c6c86c66107f8f) by [Unito](https://www.unito.io)

**Comment by manniee07** [comment]
Yeah button seems non functional.

**Comment by DavidAllenNeron** [comment]
> Yeah button seems non functional.

I still can't get it working, therefore I can't get SANA to work because the fix everyone suggests requires the Install Via Git URL

**Comment by voxelium** [comment]
I have the same problem
I click the Install via Git URL and nothing happens

**Comment by TRGLN** [comment]
Same Problem

**Comment by ltdrdata** [comment]
Please upload comfyui.log file.

**Comment by manniee07** [comment]
Where is the logfile in desktop version

> Please upload comfyui.log file.

**Comment by robinjhuang** [comment]
Please check the user guide here.
https://comfyorg.notion.site/ComfyUI-Desktop-User-Guide-1146d73d365080a49058e8d629772f0a#1486d73d365080999843ea13fda2fac1

**Comment by yahtnif** [comment]
Click the `Install via Git URL` button, get the error message in the DevTools console:

```
Uncaught Error: prompt() is and will not be supported.
```

The code that caused the error is in `comfyui-manager.js`:


```js
$el("button.cm-button", {
    type: "button",
    textContent: "Install via Git URL",
    onclick: () => {
        var url = prompt("Please enter the URL of the Git repository to install", "");

        if (url !== null) {
            install_via_git_url(url, self);
        }
    }
}),
```

Possibly related to this issue: https://github.com/electron/electron/issues/472

**Comment by ltdrdata** [comment]
> prompt() is and will not be supported.oh.

> Click the `Install via Git URL` button, get the error message in the DevTools console:
> 
> ```
> Uncaught Error: prompt() is and will not be supported.
> ```
> 
> The code that caused the error is in `comfyui-manager.js`:
> 
> ```js
> $el("button.cm-button", {
>     type: "button",
>     textContent: "Install via Git URL",
>     onclick: () => {
>         var url = prompt("Please enter the URL of the Git repository to install", "");
> 
>         if (url !== null) {
>             install_via_git_url(url, self);
>         }
>     }
> }),
> ```
> 
> Possibly related to this issue: [electron/electron#472](https://github.com/electron/electron/issues/472)

Oh... wow... I didn't aware that issue. I'll patch it.
