### ISSUE TITLE
[Bug]:  Desktop App start failed.

### ISSUE THREAD

**Issue by doncat99** [Comfy-Org/desktop#568]
### App Version

0.4.3 arm64

### Expected Behavior

App start normally

### Actual Behavior

![step1](https://github.com/user-attachments/assets/3fccd86b-09ca-4c55-aa60-8d7ba1ab3811)

after a selected a valid location,

![step2](https://github.com/user-attachments/assets/6224ffde-1789-42f6-b2cd-af92b28e37c8)

can't start.

### Steps to Reproduce

i delected the app, reinstall, no better.

### Debug Logs

```powershell
na
```

### Browser Logs

na

### Setting JSON

na

### Other

na

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-568-Bug-Desktop-App-start-failed-1686d73d36508105a0c0dc72f60942f7) by [Unito](https://www.unito.io)

**Comment by Neytiri7** [comment]
I'm constantly being reset.
I think I'm only installing it more than 20 times right now.

**Comment by robinjhuang** [comment]
Also @Neytiri7 @doncat99 can you try 0.4.4? Just published a recent version with a fix for resets that @webfiltered put in

**Comment by Neytiri7** [comment]
> Also @Neytiri7 @doncat99 can you try 0.4.4? Just published a recent version with a fix for resets that @webfiltered put in

https://github.com/Comfy-Org/desktop/issues/575

**Comment by doncat99** [comment]
> Reference in

sure.

[2024-12-26 15:17:43.690] [info]  Wrote settings to /Users/huangdon/Documents/ComfyUI/user/default/comfy.settings.json: {
  "Comfy-Desktop.AutoUpdate": true,
  "Comfy-Desktop.SendStatistics": false,
  "Comfy.ColorPalette": "dark",
  "Comfy.UseNewMenu": "Top",
  "Comfy.Workflow.WorkflowTabsPosition": "Topbar",
  "Comfy.Workflow.ShowMissingModelsWarning": true,
  "Comfy.Server.LaunchArgs": {}
}
[2024-12-26 15:17:43.690] [info]  Creating model config files in /Users/huangdon/Library/Application Support/ComfyUI/extra_models_config.yaml
[2024-12-26 15:17:43.697] [info]  Created extra_model_paths.yaml at /Users/huangdon/Library/Application Support/ComfyUI/extra_models_config.yaml
[2024-12-26 15:17:44.059] [info]  Received renderer-ready message!
[2024-12-26 15:17:59.599] [error] Unhandled exception during app startup Error: No base path selected or failed to save in config.
    at InstallationManager.resolveIssues (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27888:31)
    at async InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27805:7)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:18:04.559] [info]  App window closed. Quitting application.
[2024-12-26 15:18:09.777] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:18:09.823] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:18:09.824] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:18:14.154] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:18:14.159] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:18:14.159] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:18:14.159] [error] Unhandled exception during app startup Error: Installation issues remain after validation.
    at InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27809:45)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:18:15.509] [info]  App window closed. Quitting application.
[2024-12-26 15:18:21.640] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:18:21.685] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:18:21.685] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:18:33.938] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:18:33.942] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:18:33.943] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:18:33.943] [error] Unhandled exception during app startup Error: Installation issues remain after validation.
    at InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27809:45)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:18:38.493] [info]  App window closed. Quitting application.
[2024-12-26 15:22:23.398] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:22:23.446] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:22:23.446] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:23:53.710] [error] Unhandled exception during app startup Error: No base path selected or failed to save in config.
    at InstallationManager.resolveIssues (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27888:31)
    at async InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27805:7)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:24:04.620] [info]  App window closed. Quitting application.
[2024-12-26 15:24:15.106] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:24:15.154] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:24:15.154] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:24:22.341] [error] Unhandled exception during app startup Error: No base path selected or failed to save in config.
    at InstallationManager.resolveIssues (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27888:31)
    at async InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27805:7)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:24:24.886] [info]  App window closed. Quitting application.
[2024-12-26 15:24:44.312] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:24:44.357] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:24:44.357] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:27:32.625] [error] Unhandled exception during app startup Error: No base path selected or failed to save in config.
    at InstallationManager.resolveIssues (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27888:31)
    at async InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27805:7)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:27:46.001] [info]  App window closed. Quitting application.
[2024-12-26 15:27:49.387] [info]  Validating installation. Recorded state: [installed]
[2024-12-26 15:27:49.435] [warn]  "base_path" is inaccessible or undefined.
[2024-12-26 15:27:49.435] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-26 15:28:22.373] [error] Unhandled exception during app startup Error: No base path selected or failed to save in config.
    at InstallationManager.resolveIssues (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27888:31)
    at async InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27805:7)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-26 15:28:35.711] [info]  App window closed. Quitting application.
[2024-12-27 16:54:30.376] [info]  Validating installation. Recorded state: [installed]
[2024-12-27 16:54:30.437] [warn]  "base_path" is inaccessible or undefined.
[2024-12-27 16:54:30.437] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-27 16:54:36.735] [error] Unhandled exception during app startup Error: No base path selected or failed to save in config.
    at InstallationManager.resolveIssues (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27888:31)
    at async InstallationManager.ensureInstalled (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27805:7)
    at async startApp (/Applications/ComfyUI.app/Contents/Resources/app.asar/.vite/build/main.cjs:27960:28)
[2024-12-27 16:54:38.273] [info]  App window closed. Quitting application.
[2024-12-27 16:57:33.651] [info]  Validating installation. Recorded state: [installed]
[2024-12-27 16:57:33.697] [warn]  "base_path" is inaccessible or undefined.
[2024-12-27 16:57:33.698] [info]  Validation result: isValid:false, state:installed, issues:1
[2024-12-27 16:58:42.202] [info]  App window closed. Quitting application.
[2024-12-27 16:58:42.219] [info]  Validating installation. Recorded state: [installed]

**Comment by doncat99** [comment]
> base_path

0.4.4 doesn't help me out.

below is the comfyui.log, hope it helps to figure the bug out.

[2024-12-26 15:17:16.201] [error] Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/main.py", line 11, in <module>

[2024-12-26 15:17:16.201] [error]     import utils.extra_config
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/utils/extra_config.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by doncat99** [comment]
> ~/Library/Application Support/ComfyUI/

sure thing.

# ComfyUI extra_model_paths.yaml for darwin
comfyui_desktop:
  is_default: "true"
  checkpoints: models/checkpoints/
  classifiers: models/classifiers/
  clip: models/clip/
  clip_vision: models/clip_vision/
  configs: models/configs/
  controlnet: models/controlnet/
  diffusers: models/diffusers/
  diffusion_models: models/diffusion_models/
  embeddings: models/embeddings/
  gligen: models/gligen/
  hypernetworks: models/hypernetworks/
  loras: models/loras/
  photomaker: models/photomaker/
  style_models: models/style_models/
  unet: models/unet/
  upscale_models: models/upscale_models/
  vae: models/vae/
  vae_approx: models/vae_approx/
  animatediff_models: models/animatediff_models/
  animatediff_motion_lora: models/animatediff_motion_lora/
  animatediff_video_formats: models/animatediff_video_formats/
  ipadapter: models/ipadapter/
  liveportrait: models/liveportrait/
  insightface: models/insightface/
  layerstyle: models/layerstyle/
  LLM: models/LLM/
  Joy_caption: models/Joy_caption/
  sams: models/sams/
  blip: models/blip/
  CogVideo: models/CogVideo/
  xlabs: models/xlabs/
  instantid: models/instantid/
  custom_nodes: custom_nodes/
  download_model_base: models
  base_path: /Users/huangdon/Documents/ComfyUI

**Comment by doncat99** [comment]
> Hi @doncat99, thanks for posting the logs! It looks like your `extra_models_config.yaml` file may be invalid or inaccessible.
> 
> It should be located here:
> 
> ```
> ~/Library/Application Support/ComfyUI/extra_models_config.yaml
> ```
> 
> If you'd like, you can post the file here and we can take a look at what's wrong. You can also try moving the file to another folder and restarting the app - it should allow you to get past where you were stuck.


i guess I know what is going wrong.

the extra.yaml placed that the base_path is base_path: /Users/huangdon/Documents/ComfyUI. Whereas, the folder I selected from the install guidance, as the image shown below, 

![398669454-3fccd86b-09ca-4c55-aa60-8d7ba1ab3811](https://github.com/user-attachments/assets/8ab31c81-a214-40f0-ab99-27dd7c99d2cc)

is not the comfyUI folder. 

your application doesn't updated the folder I selected. but use "ComfyUI" folder as always.

**Comment by doncat99** [comment]
Another Bug.

![WX20241228-152115@2x](https://github.com/user-attachments/assets/488967da-ac12-4458-a8b6-09a3d35f1098)

and the error log shows that "user" folder is not created before using.
